# Prefix
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-features ",screen-256color:RGB"
set -as terminal-features ",tmux-256color:RGB"

# Custom
set -g status on
set -g status-position top
set -g status-justify centre
set -g status-interval 1
set -g status-right "#{pane_current_path}"
set -g status-left-length 40
set -g status-left '#{?client_prefix,#[fg=#000000]#[bg=#fbf1c7] #S ,#[fg=#fbf1c7]#[bg=#000000] #S}'
set -g window-status-format "#[fg=#3c3836,bg=#000000] #W "
set -g window-status-current-format "#[fg=#000000,bg=#ebdbb2] #W "
set -g status-style 'fg=#ebdbb2,bg=#000000'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

# Reload config
bind-key r source-file ~/.config/tmux/tmux.conf \\; display-message "~/.config/tmux/tmux.conf reloaded"

# General
set -g base-index 1
setw -g pane-base-index 2
set -g mouse on
set -g detach-on-destroy off
set -g status-position top

# Splits keep current path
bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

# Kill pane
bind-key x kill-pane

# Vim-aware pane navigation
# is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\\\S+\\\\/)?g?(view|n?vim?x?)(diff)?$'"

# bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
# bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
# bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
# bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'
#
# tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\\1/p")'
#
# if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \\
# "bind-key -n 'C-\\\\' if-shell \\"$is_vim\\" 'send-keys C-\\\\' 'select-pane -l'"
# if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \\
# "bind-key -n 'C-\\\\' if-shell \\"$is_vim\\" 'send-keys C-\\\\\\\\' 'select-pane -l'"
#
# bind-key -n 'C-Space' if-shell "$is_vim" 'send-keys C-Space' 'select-pane -t:.+'
#
# bind-key -T copy-mode-vi 'C-h' select-pane -L
# bind-key -T copy-mode-vi 'C-j' select-pane -D
# bind-key -T copy-mode-vi 'C-k' select-pane -U
# bind-key -T copy-mode-vi 'C-l' select-pane -R
# bind-key -T copy-mode-vi 'C-\\' select-pane -l
# bind-key -T copy-mode-vi 'C-Space' select-pane -t:.+

# TPM init
run '~/.tmux/plugins/tpm/tpm'
